# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code3d', models.CharField(max_length=3)),
                ('code2d', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Domain')),
                ('source_language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='aggregator.Language')),
                ('target_language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='aggregator.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('homepage', models.URLField()),
                ('search_url', models.URLField()),
                ('languages', models.ManyToManyField(to='aggregator.Language')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Website'),
        ),
        migrations.AddField(
            model_name='record',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Search'),
        ),
        migrations.AddField(
            model_name='record',
            name='terms',
            field=models.ManyToManyField(related_name='terms', to='aggregator.Term'),
        ),
        migrations.AddField(
            model_name='record',
            name='translations',
            field=models.ManyToManyField(related_name='translations', to='aggregator.Term'),
        ),
    ]
