# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='domain',
        ),
        migrations.AddField(
            model_name='record',
            name='domain',
            field=models.ManyToManyField(to='aggregator.Domain'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='domain',
        ),
        migrations.AddField(
            model_name='search',
            name='domain',
            field=models.ManyToManyField(to='aggregator.Domain'),
        ),
    ]
