# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20161218_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='domain',
            new_name='domains',
        ),
    ]
