# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code3d', models.CharField(max_length=3)),
                ('code2d', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(verbose_name='last update')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('homepage', models.URLField()),
                ('search_rul', models.URLField()),
                ('languages', models.ManyToManyField(to='search.Language')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='terms',
            field=models.ManyToManyField(related_name='terms', to='search.Term'),
        ),
        migrations.AddField(
            model_name='record',
            name='translations',
            field=models.ManyToManyField(related_name='translations', to='search.Term'),
        ),
        migrations.AddField(
            model_name='record',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Website'),
        ),
    ]
