# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='search_rul',
            new_name='search_url',
        ),
    ]
